### PR TITLE
Fix project dependencies so it could be cloned and built locally

### PR DESCRIPTION
**Pull request by LelouchHe**
The current dependencies seem broken. Once cloned to local, it fails to `yarn install` due to dependencies build errors.

Below are the errors from `yarn install`

➤ YN0009: │ msgpackr-extract@npm:1.0.15 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\longh\AppData\Local\Temp\xfs-41b8c800\build.log)
➤ YN0009: │ lmdb-store@npm:1.6.13 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\longh\AppData\Local\Temp\xfs-7d83501c\build.log)

The major error from build log is:

\logseq-inbox-telegram-plugin\node_modules\nan\nan_callbacks.h(55,23): error C2039: 'AccessorSignature': is not a member of 'v8' [\logseq-inbox-telegram-plugin\node_modules\lmdb-store\build\lmdb.vcxproj]

Based on [nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’ #942](https://github.com/nodejs/nan/issues/942), packages are updated to fix this error.

It also add `.yarnrc.yml` and `.yarn/` to .gitignore

### CODE REVIEW

**Comment by shady2k** [comment]
It's strange, but I have no errors. How can I reproduce this problem?
- Clone the repository
- Execute yarn install
Is it right?

**Comment by LelouchHe** [comment]
> It's strange, but I have no errors. How can I reproduce this problem?
> 
> * Clone the repository
> * Execute yarn install
>   Is it right?

Yes. My dev environment is new, since I just installed the node and other tools before I cloned this repository.

**Comment by shady2k** [comment]
What node version do you use?

**Comment by shady2k** [comment]
It forces me to install Buffer.

@parcel/resolver-default: Auto installing polyfill for Node builtin module "buffer"...

  /Users/shady/Documents/repos/logseq-inbox-telegram-plugin/node_modules/axios/lib/helpers/toFormData.js:128:74
    127 |     if (utils.isArrayBuffer(value) || utils.isTypedArray(value)) {
  > 128 |       return useBlob && typeof Blob === 'function' ? new Blob([value]) : Buffer.from(value);
  >     |                                                                          ^^^^^^ used here
    129 |     }
    130 | 

  📝 Learn more: https://parceljs.org/features/node-emulation/#polyfilling-%26-excluding-builtin-node-modules

Installing buffer...

  "devDependencies": {
    "buffer": "^5.5.0",
    "parcel": "^2.8.3"
  },

**Comment by LelouchHe** [comment]
> It forces me to install Buffer.
> 
> @parcel/resolver-default: Auto installing polyfill for Node builtin module "buffer"...
> 
> /Users/shady/Documents/repos/logseq-inbox-telegram-plugin/node_modules/axios/lib/helpers/toFormData.js:128:74 127 | if (utils.isArrayBuffer(value) || utils.isTypedArray(value)) {
> 
> > 128 |       return useBlob && typeof Blob === 'function' ? new Blob([value]) : Buffer.from(value);
> > |                                                                          ^^^^^^ used here
> > 129 |     }
> > 130 |
> 
> 📝 Learn more: https://parceljs.org/features/node-emulation/#polyfilling-%26-excluding-builtin-node-modules
> 
> Installing buffer...
> 
> "devDependencies": { "buffer": "^5.5.0", "parcel": "^2.8.3" },

it does the same thing for mine when i continued to update the code. do you know whether we should update that and others?

**Pull request closed without merging**
